api_root_path: /
auth_algs:
- ES256
auth_check_claims:
  email: null
  exp: null
  iat: null
  name: null
auth_key: '{}'
auth_map_claims: {}
auto_reload: true
cors_allow_credentials: false
cors_allowed_headers: []
cors_allowed_methods: []
cors_allowed_origins: []
dataset_overview_event_topic: metadata
dataset_overview_event_type: metadata_dataset_overview
datasets_collection: datasets
db_connection_str: '**********'
db_name: dev-db
docs_url: /docs
download_access_url: http://127.0.0.1:8080/download_access
host: 127.0.0.1
kafka_servers:
- kafka:9092
log_level: info
openapi_url: /openapi.json
port: 8080
service_instance_id: '1'
service_name: wps
work_package_signing_key: '**********'
work_package_valid_days: 30
work_packages_collection: workPackages
workers: 1
