api_root_path: /
auth_algs:
- ES256
auth_check_claims:
  email: null
  exp: null
  iat: null
  name: null
auth_key: '{}'
auth_map_claims: {}
auto_reload: true
cors_allow_credentials: false
cors_allowed_headers: []
cors_allowed_methods: []
cors_allowed_origins: []
dataset_change_event_topic: metadata_datasets
dataset_deletion_event_type: dataset_deleted
dataset_upsertion_event_type: dataset_created
datasets_collection: datasets
db_connection_str: '**********'
db_name: dev-db
docs_url: /docs
download_access_url: http://127.0.0.1:8080/download-access
host: 127.0.0.1
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_level: info
openapi_url: /openapi.json
port: 8080
service_instance_id: wps_1
service_name: wps
work_package_signing_key: '**********'
work_package_valid_days: 30
work_packages_collection: workPackages
workers: 1
