api_root_path: /
api_route: /api
auto_reload: true
cors_allow_credentials: false
cors_allowed_headers: []
cors_allowed_methods: []
cors_allowed_origins: []
db_connection_str: '**********'
db_name: dev_db
db_url: mongodb://mongodb:27017/
docs_url: /docs
host: 0.0.0.0
log_level: info
openapi_url: /openapi.json
port: 8080
service_name: wps
work_packages_collection: workPackages
workers: 1
