services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    init: true
    privileged: true

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # define environment variables
    environment:
      WPS_CONFIG_YAML: /workspace/.devcontainer/.dev_config.yaml

  mongodb:
    image: mongo:7.0.7
    restart: unless-stopped
    volumes:
      - mongo_fs:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    restart: unless-stopped
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/

volumes:
  mongo_fs: {}
