version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3.9
        PACKAGE_NAME: "work_package_service"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    init: true
    privileged: true

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # define environment variables
    environment:
      AWORK_PACKAGE_SERVICE_HOST: "0.0.0.0"
      AWORK_PACKAGE_SERVICE_PORT: "8080"
      WORK_PACKAGE_SERVICE_DB_URL: mongodb://mongodb:27017/
      WORK_PACKAGE_SERVICE_CONFIG_YAML: /workspace/.devcontainer/.dev_config.yaml

  mongodb:
    image: mongo:6.0.3
    restart: unless-stopped
    volumes:
      - mongo_fs:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/

volumes:
  mongo_fs: {}
