[project]
name = "wps"
version = "11.1.0"
description = "Work Package Service"
dependencies = [
    "ghga-event-schemas~=13.0.0",
    "ghga-service-commons[api,auth,crypt]>=7.0",
    "hexkit[akafka,mongodb,opentelemetry-akafka,opentelemetry-mongodb,opentelemetry-fastapi]>=8.4",
    "httpx>=0.28",
    "typer>=0.26",
]

[project.urls]
Repository = "https://github.com/ghga-de/work-package-service"

[project.scripts]
wps = "wps.__main__:cli"
