# This file is only needed if your repository uses FastAPI
name: Check if OpenAPI spec is up to date

on: push

jobs:
  static-code-analysis:
    name: Check OpenAPI spec

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Common steps
        id: common
        uses: ghga-de/gh-action-common@v6

      - name: Check openapi.yaml
        id: check-openapi-docs
        run: |
          export ${{ steps.common.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.common.outputs.CONFIG_YAML }}"

          ./scripts/update_openapi_docs.py --check
